version: '3.8'

services:
  backend:
    build: ./backend
    container_name: NIDriveBot-backend
    ports:
      - "7070:7070"
    # Удаляем монтирование томов для исправления ошибки в Windows Docker Desktop
    # volumes:
    #  - ./backend:/app
    #  - uploads_data:/app/uploads
    #  - db_data:/app/db
    environment:
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-me}
      - UPLOAD_DIR=/app/uploads
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./db/NIDriveBot.db}
      - DATABASE_PATH=/app/db/NIDriveBot.db
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: NIDriveBot-frontend
    ports:
      - "7071:7071"
    # Удаляем монтирование томов для исправления ошибки в Windows Docker Desktop
    # volumes:
    #  - ./frontend:/app
    #  - /app/node_modules
    environment:
      - VITE_API_URL=https://drive.nicorp.tech/api/v1
      - VITE_TEST_MODE=false
      - VITE_TELEGRAM_BOT_NAME=nidrivebot
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  uploads_data:
    name: NIDriveBot-uploads
  db_data:
    name: NIDriveBot-database
